---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Download Xdebug.
  get_url:
    url: "http://xdebug.org/files/xdebug-{{ php_xdebug_version }}.tgz"
    dest: "{{ workspace }}"

- name: Untar Xdebug.
  command: >
    tar -C {{ workspace }} -xvzf {{ workspace }}/xdebug-{{ php_xdebug_version }}.tgz
    creates={{ workspace }}/xdebug-{{ php_xdebug_version }}/README

- name: Build Xdebug.
  shell: >
    {{ item }}
    chdir={{ workspace }}/xdebug-{{ php_xdebug_version }}
    creates={{ workspace }}/xdebug-{{ php_xdebug_version }}/modules/xdebug.so
  with_items:
    - phpize
    - ./configure
    - make
  notify: restart webserver

- name: Ensure Xdebug module path exists.
  file:
    path: "{{ php_xdebug_module_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Move Xdebug module into place.
  shell: >
    cp {{ workspace }}/xdebug-{{ php_xdebug_version }}/modules/xdebug.so {{ php_xdebug_module_path }}/xdebug.so
    creates={{ php_xdebug_module_path }}/xdebug.so
  notify: restart webserver

- include: configure.yml
